"use client";

import { useEffect, useMemo, useState } from "react";
import { clientApi, formatDate } from "@/lib/client-api";
import type { CaseSummary } from "@/lib/types";
import { Card, EmptyState, Icon, PageHeader } from "@/components/ui";

export default function B04Page() {
  const [items, setItems] = useState<CaseSummary[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { clientApi<CaseSummary[]>("/cases/recorded").then(setItems).finally(() => setLoading(false)); }, []);
  const rows = useMemo(() => items.filter((item) => !query || `${item.student_snapshot?.name} ${item.seq} ${item.details}`.toLowerCase().includes(query.toLowerCase())), [items, query]);
  return <div className="mx-auto max-w-[1440px]"><PageHeader eyebrow="Rekod rasmi" title="Buku Rekod Disiplin · B04" description="Senarai kesalahan yang telah diterima dan direkod. Kes yang ditolak tidak termasuk dalam daftar ini." actions={<button type="button" onClick={() => window.print()} className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-brand-200 bg-white px-4 text-sm font-semibold text-brand-800 hover:bg-brand-50"><Icon name="printer" size={17} />Cetak daftar</button>} /><Card className="overflow-hidden"><div className="border-b border-ink-100 bg-brand-50/60 p-4"><label className="relative block max-w-xl"><span className="sr-only">Cari rekod B04</span><Icon name="search" size={17} className="pointer-events-none absolute left-3 top-3.5 text-ink-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari nama murid, nombor kes, atau butiran…" className="h-11 w-full rounded-lg border border-ink-200 bg-white pl-10 pr-3 text-sm outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-200" /></label></div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-white text-[10px] font-bold uppercase tracking-[0.14em] text-ink-600"><tr><th className="px-5 py-3">Bil.</th><th className="px-5 py-3">Tarikh</th><th className="px-5 py-3">Murid</th><th className="px-5 py-3">Butiran</th><th className="px-5 py-3">Mata</th><th className="px-5 py-3">Kes</th></tr></thead><tbody className="divide-y divide-ink-100">{rows.map((item, index) => <tr key={item.id} className="hover:bg-brand-50/50"><td className="px-5 py-4 font-mono text-xs text-ink-500">{index + 1}</td><td className="px-5 py-4 text-xs text-ink-600">{formatDate(item.created_at)}</td><td className="px-5 py-4"><span className="font-semibold text-brand-950">{item.student_snapshot?.name}</span><span className="mt-1 block text-xs text-ink-500">{item.student_snapshot?.kelas_label}</span></td><td className="max-w-[420px] px-5 py-4 text-ink-700">{item.details || "-"}</td><td className="px-5 py-4 font-mono font-semibold text-gold-800">{item.points}</td><td className="px-5 py-4"><a href={`/kes/${item.id}`} className="text-xs font-bold text-brand-700 hover:text-gold-700">K-{String(item.seq).padStart(4, "0")}</a></td></tr>)}</tbody></table>{!loading && !rows.length ? <EmptyState icon="archive" title="Daftar masih kosong" description="Kes yang telah direkod akan muncul dalam B04." /> : null}</div><div className="border-t border-ink-100 px-5 py-3 text-xs text-ink-500">{rows.length} rekod dipaparkan</div></Card></div>;
}
