"""initial schema

Revision ID: e5b81bacc6f9
Revises: 
Create Date: 2026-09-03 18:31:21.253062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e5b81bacc6f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('student_source_id', sa.Integer(), nullable=False),
    sa.Column('student_snapshot', sa.JSON(), nullable=False),
    sa.Column('reporter_sub', sa.String(length=255), nullable=False),
    sa.Column('reporter_name', sa.String(length=255), nullable=False),
    sa.Column('reporter_role', sa.String(length=30), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('warning_level', sa.String(length=10), nullable=False),
    sa.Column('meeting', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_reporter_sub'), 'cases', ['reporter_sub'], unique=False)
    op.create_index(op.f('ix_cases_seq'), 'cases', ['seq'], unique=True)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index(op.f('ix_cases_student_source_id'), 'cases', ['student_source_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_sub', sa.String(length=255), nullable=True),
    sa.Column('recipient_role', sa.String(length=30), nullable=True),
    sa.Column('ntype', sa.String(length=30), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_recipient_role'), 'notifications', ['recipient_role'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_sub'), 'notifications', ['recipient_sub'], unique=False)
    op.create_table('pengawas_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pengawas_accounts_email'), 'pengawas_accounts', ['email'], unique=True)
    op.create_table('students_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('ic_number', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('tingkatan', sa.Integer(), nullable=False),
    sa.Column('kelas', sa.String(length=50), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', name='uq_students_source_id')
    )
    op.create_index(op.f('ix_students_cache_name'), 'students_cache', ['name'], unique=False)
    op.create_index(op.f('ix_students_cache_source_id'), 'students_cache', ['source_id'], unique=False)
    op.create_table('b02_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('fill_by', sa.String(length=255), nullable=False),
    sa.Column('fill_role', sa.String(length=30), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_b02_forms_case_id'), 'b02_forms', ['case_id'], unique=False)
    op.create_table('case_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('doc_code', sa.String(length=10), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'doc_code', name='uq_case_docs')
    )
    op.create_index(op.f('ix_case_docs_case_id'), 'case_docs', ['case_id'], unique=False)
    op.create_table('case_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('by_name', sa.String(length=255), nullable=False),
    sa.Column('by_role', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_events_case_id'), 'case_events', ['case_id'], unique=False)
    op.create_table('case_offences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_offences_case_id'), 'case_offences', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_offences_case_id'), table_name='case_offences')
    op.drop_table('case_offences')
    op.drop_index(op.f('ix_case_events_case_id'), table_name='case_events')
    op.drop_table('case_events')
    op.drop_index(op.f('ix_case_docs_case_id'), table_name='case_docs')
    op.drop_table('case_docs')
    op.drop_index(op.f('ix_b02_forms_case_id'), table_name='b02_forms')
    op.drop_table('b02_forms')
    op.drop_index(op.f('ix_students_cache_source_id'), table_name='students_cache')
    op.drop_index(op.f('ix_students_cache_name'), table_name='students_cache')
    op.drop_table('students_cache')
    op.drop_index(op.f('ix_pengawas_accounts_email'), table_name='pengawas_accounts')
    op.drop_table('pengawas_accounts')
    op.drop_index(op.f('ix_notifications_recipient_sub'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_role'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_cases_student_source_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_seq'), table_name='cases')
    op.drop_index(op.f('ix_cases_reporter_sub'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###