"""add counselling and punishment

Revision ID: eef329e83923
Revises: e5b81bacc6f9
Create Date: 2026-09-03 21:27:52.985556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eef329e83923'
down_revision: Union[str, None] = 'e5b81bacc6f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('cases', sa.Column('counselling', sa.JSON(), nullable=True))
    op.add_column('cases', sa.Column('punishment', sa.JSON(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'punishment')
    op.drop_column('cases', 'counselling')
    # ### end Alembic commands ###