GURU_BIASA = "guru_biasa"
GURU_DISIPLIN = "guru_disiplin"
PENTADBIR = "pentadbir"
SUPER_ADMIN = "super_admin"
PENGAWAS = "pengawas"

STAFF_ROLES = frozenset({GURU_BIASA, GURU_DISIPLIN, PENTADBIR, SUPER_ADMIN})
MANAGER_ROLES = frozenset({GURU_DISIPLIN, PENTADBIR, SUPER_ADMIN})
ADMIN_ROLES = frozenset({PENTADBIR, SUPER_ADMIN})

MANAGER_ROLE_ORDER = (GURU_DISIPLIN, PENTADBIR, SUPER_ADMIN)
ADMIN_ROLE_ORDER = (PENTADBIR, SUPER_ADMIN)